### ISSUE TITLE
Old is gold...

### ISSUE THREAD

**Issue by Mid90sAhsan** [Hitheshaum/OBCI_Interrupt#1]
http://openbci.com/forum/index.php?p=/discussion/418/using-interrupts-vs-polling-of-ads1299/p1

Back in the days you posted a question is the above link, you said DRDY pin is high and not being low. But you happen to resolve the problem. 
**You said:"EDIT: Sorry my bad. I was using the wrong library settings in the tools."**

Can you tell what were the library settings. We are stuck at same place. 

Thanks.

**Comment by Hitheshaum** [comment]
Hi Ahsan,
If I remember correctly, my problem back then was a very silly one.
In PicKIT IDE, in tools I selected the wrong board configuration (something
other than openBCI board config). This made the pin config definitions
different and so it didn't work. When I selected the openBCI board, it all
started working properly.

Regards,
Hithesh

**Comment by Mid90sAhsan** [comment]
Hey Hithesh,
Thanks for replying. I will try it and let you know if it works.

Regards, 
Ahsan

**Comment by Mid90sAhsan** [comment]
Hey Hithesh,
Sorry to bother you again, but I can't find the board configurations in Pickit IDE. I am using MPLab X IDE and it has no option for board configurations.
Before I was using Arduino to upload the code, it has the board selection option. But it gives error in flashing program. 
So now I am using pickit3 to upload the code in the pic32. I am have the same problem, the Data-ready pin doesn't go low. Processing GUI connects with the device but it doesn't gives any data. 
Can you help me, figuring out where can I select the board?

Thanks,
Ahsan

**Comment by Mid90sAhsan** [comment]
Hey Hithest,
I resolved it. Its working.

Thanks, 
Ahsan

**Comment by Hitheshaum** [comment]
great
